name: Hello World
on: [push]
jobs:
  Hello-World-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World!"
      - name: Current date and time
        run: date
      - name: Directory content
        run: ls -l